export 'package:bloc/bloc.dart';
export 'package:just_audio/just_audio.dart';
export 'package:music_player/ui/home/cubit/home_state.dart';
export 'package:on_audio_query/on_audio_query.dart';
export 'package:audio_video_progress_bar/audio_video_progress_bar.dart';
export 'package:flutter/material.dart';
// export 'package:flutter/cupertino.dart';
export '/ui/tracks/presentation/tracks_screen.dart';
export 'package:flutter_bloc/flutter_bloc.dart';
export 'package:music_player/data/constants/constants.dart';
export 'package:music_player/ui/home/cubit/home_cubit.dart';
export '/ui/widgets/music_items.dart';
export 'package:go_router/go_router.dart';
export 'package:music_player/ui/home/presentation/home_screen.dart';
export '../../ui/splash/presentation/splash_screen.dart';
export 'package:music_player/ui/splash/cubit/splash_state.dart';
export 'package:music_player/ui/background/presentation/background_wrapper.dart';
export 'package:music_player/utils/tools/app_router.dart';
export 'package:permission_handler/permission_handler.dart';
export 'package:music_player/ui/splash/cubit/splash_cubit.dart';
export 'package:music_player/data/theme/my_theme.dart';
export 'package:like_button/like_button.dart';
export 'dart:async';
export 'package:music_player/ui/widgets/adition_control.dart';
export 'dart:io';

export 'package:flutter/widgets.dart';